favicon: /favicon.svg
cover: /cover.svg

latin_font: '"SF Pro Text", "Segoe UI", Arial'
cjk_font_sans: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans CJK SC", sans-serif'
cjk_font_serif: '"Songti SC", "STSong", "SimSun", "Noto Serif CJK SC", serif'
cjk_font_default: serif

posts_path: /blog

menu:
  Posts: /blog
  Tags: /blog/tags
  Categories: /blog/categories
  Archives: /blog/archives

header_menu:
  Posts: /blog
  Tags: /blog/tags
  Categories: /blog/categories
  Archives: /blog/archives

posts_category_depth: 1
do_not_show_parent_category: true
show_description: true
